# Generated by Django 5.2.9 on 2026-01-06 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('product', models.CharField()),
                ('amount', models.IntegerField()),
                ('category', models.CharField()),
                ('description', models.CharField()),
                ('date', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
    ]
